name: Run camisetas_bot

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/20 * * * *'

    
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: install req
      run: pip install tweepy 
    - name: run the bot
      env: 
        TW_CONSUMER_KEY: ${{ secrets.TW_CONSUMER_KEY }}
        TW_CONSUMER_SECRET: ${{ secrets.TW_CONSUMER_KEY }}
        TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
        TW_ACCESS_TOKEN_SECRET: ${{ secrets.TW_ACCESS_TOKEN_SECRET }} 
      run: python camisetas_bot.py --tweet